(TeX-add-style-hook "project_1"
 (lambda ()
    (LaTeX-add-labels
     "fig:character_per_words")
    (TeX-add-symbols
     "R")
    (TeX-run-style-hooks
     "natbib"
     "geometry"
     "margin=2cm"
     "multirow"
     "fix-cm"
     "booktabs"
     "subfig"
     "epstopdf"
     "caption"
     "textfont=it"
     "up"
     "labelfont=bf"
     "small"
     "hang"
     "xcolor"
     "svgnames"
     "graphicx"
     "pdftex"
     "bm"
     "amsthm"
     "amsfonts"
     "amsmath"
     "microtype"
     "expansion=true"
     "protrusion=true"
     "babel"
     "english"
     "lipsum"
     ""
     "inputenc"
     "utf8"
     "latex2e"
     "art10"
     "article"
     "a4paper")))

